trigger:
  branches:
    include: ["master"]
  paths:
    exclude: ["doc", "*.md"]

queue: VSEng-MicroBuildVS2017

steps:
- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    esrpSigning: true
    zipSources: false

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**\*.sln'
    feedsToUse: config
    nugetConfigPath: src/nuget.config
    externalFeedCredentials: mseng VS-PrivateAssemblies
  displayName: Nuget restore packages

- task: VSBuild@1
  inputs:
    vsVersion: 15.0
    msbuildArgs: /t:build,pack
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
  displayName: Build Visual Studio solution

- task: VSTest@2
  inputs:
    testAssemblyVer2: bin/**/$(BuildConfiguration)/**/*tests*.dll
    codeCoverageEnabled: true
    runInParallel: true
    vsTestVersion: latest
    pathtoCustomTestAdapters: $(Build.SourcesDirectory)\bin\Microsoft.VisualStudio.Sdk.TestFramework.Tests\$(BuildConfiguration)\net46

- task: MicroBuildCleanup@1
  condition: succeededOrFailed()

- task: CopyFiles@1
  inputs:
    Contents: |
      bin/**/$(BuildConfiguration)/*.nupkg
    TargetFolder: $(Build.ArtifactStagingDirectory)/deployables
    flattenFolders: true
  displayName: Collecting deployables

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/deployables
    ArtifactName: deployables
    ArtifactType: Container
  displayName: Publish deployables artifacts
  condition: and(succeeded(), ne(variables['system.pullrequest.isfork'], true))
