steps:
- task: NuGetCommand@2
  displayName: Push packages to CI feed
  inputs:
    command: push
    packagesToPush: bin/Packages/$(BuildConfiguration)/NuGet/*.nupkg
    nuGetFeedType: internal
    publishVstsFeed: $(ci_feed)
    allowPackageConflicts: true
  condition: and(succeeded(), eq(variables['push_to_ci'], 'true'), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))
